global:
  scrape_interval: 2s
  evaluation_interval: 2s


scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:9000']
  - job_name: 'approval-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['approval-service:8044'] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: 'Approval Service'